name: CI - Calculator with Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # 2. Настраиваем Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # 3. Проверка версии Docker
      - name: Check Docker version
        run: docker --version
      
      # 4. Сборка Docker образа приложения
      - name: Build Docker image
        run: docker build -t calculator .
      
      # 5. Запуск контейнера тестов отдельно
      - name: Run tests
        run: docker compose run --rm tests
